input {
    tcp {
        port => 5000
        codec => json_lines
    }
}

filter {
    grok {
        match => { "message" => "%{TIMESTAMP_ISO8601:timestamp} \[%{DATA:thread}\] %{LOGLEVEL:loglevel} %{DATA:logger} - %{GREEDYDATA:message}" }
    }
}

output {
    elasticsearch {
        hosts => ["elasticsearch:9200"]
        index => "vent-logs-%{+YYYY.MM.dd}"
    }
}
